import { CREATE_TICKET, DELETE_TICKET, UPDATE_TICKET } from "./ticket.mutation"
import { GET_TICKETS, GET_TICKET_BY_ID, GET_TICKET_BY_TITLE } from "./ticket.query"

export { CREATE_TICKET, UPDATE_TICKET, DELETE_TICKET, GET_TICKETS, GET_TICKET_BY_TITLE, GET_TICKET_BY_ID }
