import {
    CREATE_PROJECT, DELETE_PROJECT, UPDATE_PROJECT
} from "./project.mutation"
import { GET_PROJECT, GET_PROJECT_BY_ID, GET_PROJECT_BY_OWNER, GET_PROJECT_BY_TITLE } from "./project.query"


export {
    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    GET_PROJECT,
    GET_PROJECT_BY_ID,
    GET_PROJECT_BY_TITLE,
    GET_PROJECT_BY_OWNER
}

